In [1]:
import numpy as np


In [2]:
print("Creer un tableau aléatoire de shape (3, 5)")
x = np.random.randint(20, size=(3,5))


Creer un tableau aléatoire de shape (3, 5)


In [3]:
print(x)

[[ 2  1  1 15  0]
 [15 11  6 10 18]
 [15  5 18 13 18]]


In [4]:
print("Modifier le shape à (5, 3)")
x = x.reshape(5, 3)
print(x)

Modifier le shape à (5, 3)
[[ 2  1  1]
 [15  0 15]
 [11  6 10]
 [18 15  5]
 [18 13 18]]


In [5]:
print("Est-ce que c'est possible de modifier le shape à (4, 5)  : non")

Est-ce que c'est possible de modifier le shape à (4, 5)  : non


In [6]:
print("Creer un tableau qui contient les valeurs de 1 à 9 avec np.arange et donner lui un shape de (3, 3)")
y = np.arange(1,10).reshape((3,3))


Creer un tableau qui contient les valeurs de 1 à 9 avec np.arange et donner lui un shape de (3, 3)


In [7]:
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print("Faites la somme des 2 tableaux")
print(x + y)

Faites la somme des 2 tableaux


ValueError: operands could not be broadcast together with shapes (5,3) (3,3) 

In [9]:
print("Choisi un sous tableau aléatoire et extrait le")
z = np.random.randint(20, size=(4,4))


Choisi un sous tableau aléatoire et extrait le


In [10]:
print(z)
print("extraction des indices 0,3 des lignes 0 et 3 de z")
print(z[[[0],[3]], [0,3]])

[[12 16 15 19]
 [15  9  2  4]
 [18  8 12 11]
 [16  8  5  1]]
extraction des indices 0,3 des lignes 0 et 3 de z
[[12 19]
 [16  1]]
